name: Notebooks

on: [push, pull_request]
#on:
#    schedule:
#      # 4am daily
#      - cron:  '0 1 * * *'

jobs:

  build-and-test:
    name: check examples
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v1.2.0
        with:
         activate-environment: pyross
         environment-file: environment.yml
         # auto-activate-base: true
      - name: make-pyross
        shell: bash -l {0}
        run: |
          conda activate pyross
          make
      - name: testing-tsi
        shell: bash -l {0}
        run: |
          make nbtest -e path="examples/tsi/" recursive=False
